[target.wasm32-unknown-emscripten]
rustflags = [
    "-C",
    "link-args=-o playground.js",
    "-C",
    "link-args=-s EXPORTED_FUNCTIONS=['_load_ruby_script','_main']",
    "-C",
    "link-args=-s EXPORTED_RUNTIME_METHODS=['ccall','cwrap']",
    "-C",
    "link-args=-s MODULARIZE=0",
]
